services:
  app:
    ports:
      - 5432:5432
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: mitglied-app
      POSTGRES_PASSWORD: mitglied
      POSTGRES_USER: mitglied