services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    ports:
      - "5433:5432" # Ändere den Host-Port auf 5433, um Konflikte zu vermeiden
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mitglied
      POSTGRES_DB: MitgliederDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: